### ISSUE TITLE
 at BalancesTransferEvent.get asV269 ?

### ISSUE THREAD

**Issue by yangmiok** [subsquid/squid-template#10]
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(this.isV269)

    at BalancesTransferEvent.get asV269 [as asV269] (/Users/polkadot/Desktop/project/squid-template/lib/types/events.js:24:30)
    at BalancesTransferEvent.get asLatest [as asLatest] (/Users/polkadot/Desktop/project/squid-template/lib/types/events.js:33:21)
    at getTransferEvent (/Users/polkadot/Desktop/project/squid-template/lib/processor.js:71:18)
    at Array.<anonymous> (/Users/polkadot/Desktop/project/squid-template/lib/processor.js:34:22)
    at /Users/polkadot/Desktop/project/squid-template/node_modules/@subsquid/substrate-processor/lib/processor.js:189:51
    at /Users/polkadot/Desktop/project/squid-template/node_modules/@subsquid/substrate-processor/lib/db.js:62:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
```

**Comment by RaekwonIII** [comment]
Thank you for reporting this, I have opened a PR to fix this issue:
https://github.com/subsquid/squid-template/pull/12
You can fix it yourself while waiting. Simply re-run the typegen commands:

```bash
npx squid-substrate-metadata-explorer \
  --chain wss://kusama-rpc.polkadot.io \
  --archive https://kusama.indexer.gc.subsquid.io/v4/graphql \
  --out kusamaVersions.json
```
and
```bash
npx squid-substrate-typegen typegen.json
```
And apply the changes I have done to the getter function:
```typescript
function getTransferEvent(ctx: EventHandlerContext): TransferEvent {
  const event = new BalancesTransferEvent(ctx);
  if (event.isV1020) {
    const [from, to, amount] = event.asV1020;
    return { from, to, amount };
  }
  if (event.isV1050) {
    const [from, to, amount] = event.asV1050;
    return { from, to, amount };
  }
  if (event.isV9130) {
    const { from, to, amount } = event.asV9130;
    return { from, to, amount };
  }
  return event.asLatest;
}
```
